/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnitsRouteImport } from './routes/units'
import { Route as TenantsRouteImport } from './routes/tenants'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnitsIndexRouteImport } from './routes/units.index'
import { Route as TenantsIndexRouteImport } from './routes/tenants.index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as ContractsIndexRouteImport } from './routes/contracts.index'
import { Route as UnitsIdRouteImport } from './routes/units.$id'
import { Route as TenantsIdRouteImport } from './routes/tenants.$id'
import { Route as SettingsAboutRouteImport } from './routes/settings.about'
import { Route as ContractsIdRouteImport } from './routes/contracts.$id'

const UnitsRoute = UnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsRoute = TenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitsIndexRoute = UnitsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UnitsRoute,
} as any)
const TenantsIndexRoute = TenantsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantsRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const ContractsIndexRoute = ContractsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContractsRoute,
} as any)
const UnitsIdRoute = UnitsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => UnitsRoute,
} as any)
const TenantsIdRoute = TenantsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TenantsRoute,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SettingsRoute,
} as any)
const ContractsIdRoute = ContractsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ContractsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contracts': typeof ContractsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tenants': typeof TenantsRouteWithChildren
  '/units': typeof UnitsRouteWithChildren
  '/contracts/$id': typeof ContractsIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/tenants/$id': typeof TenantsIdRoute
  '/units/$id': typeof UnitsIdRoute
  '/contracts/': typeof ContractsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/tenants/': typeof TenantsIndexRoute
  '/units/': typeof UnitsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/reports': typeof ReportsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/contracts/$id': typeof ContractsIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/tenants/$id': typeof TenantsIdRoute
  '/units/$id': typeof UnitsIdRoute
  '/contracts': typeof ContractsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/tenants': typeof TenantsIndexRoute
  '/units': typeof UnitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contracts': typeof ContractsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tenants': typeof TenantsRouteWithChildren
  '/units': typeof UnitsRouteWithChildren
  '/contracts/$id': typeof ContractsIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/tenants/$id': typeof TenantsIdRoute
  '/units/$id': typeof UnitsIdRoute
  '/contracts/': typeof ContractsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/tenants/': typeof TenantsIndexRoute
  '/units/': typeof UnitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contracts'
    | '/dashboard'
    | '/login'
    | '/maintenance'
    | '/notifications'
    | '/payments'
    | '/reports'
    | '/settings'
    | '/sitemap.xml'
    | '/tenants'
    | '/units'
    | '/contracts/$id'
    | '/settings/about'
    | '/tenants/$id'
    | '/units/$id'
    | '/contracts/'
    | '/settings/'
    | '/tenants/'
    | '/units/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/maintenance'
    | '/notifications'
    | '/payments'
    | '/reports'
    | '/sitemap.xml'
    | '/contracts/$id'
    | '/settings/about'
    | '/tenants/$id'
    | '/units/$id'
    | '/contracts'
    | '/settings'
    | '/tenants'
    | '/units'
  id:
    | '__root__'
    | '/'
    | '/contracts'
    | '/dashboard'
    | '/login'
    | '/maintenance'
    | '/notifications'
    | '/payments'
    | '/reports'
    | '/settings'
    | '/sitemap.xml'
    | '/tenants'
    | '/units'
    | '/contracts/$id'
    | '/settings/about'
    | '/tenants/$id'
    | '/units/$id'
    | '/contracts/'
    | '/settings/'
    | '/tenants/'
    | '/units/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContractsRoute: typeof ContractsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  NotificationsRoute: typeof NotificationsRoute
  PaymentsRoute: typeof PaymentsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TenantsRoute: typeof TenantsRouteWithChildren
  UnitsRoute: typeof UnitsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/units': {
      id: '/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof UnitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants': {
      id: '/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof TenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/units/': {
      id: '/units/'
      path: '/'
      fullPath: '/units/'
      preLoaderRoute: typeof UnitsIndexRouteImport
      parentRoute: typeof UnitsRoute
    }
    '/tenants/': {
      id: '/tenants/'
      path: '/'
      fullPath: '/tenants/'
      preLoaderRoute: typeof TenantsIndexRouteImport
      parentRoute: typeof TenantsRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/contracts/': {
      id: '/contracts/'
      path: '/'
      fullPath: '/contracts/'
      preLoaderRoute: typeof ContractsIndexRouteImport
      parentRoute: typeof ContractsRoute
    }
    '/units/$id': {
      id: '/units/$id'
      path: '/$id'
      fullPath: '/units/$id'
      preLoaderRoute: typeof UnitsIdRouteImport
      parentRoute: typeof UnitsRoute
    }
    '/tenants/$id': {
      id: '/tenants/$id'
      path: '/$id'
      fullPath: '/tenants/$id'
      preLoaderRoute: typeof TenantsIdRouteImport
      parentRoute: typeof TenantsRoute
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/contracts/$id': {
      id: '/contracts/$id'
      path: '/$id'
      fullPath: '/contracts/$id'
      preLoaderRoute: typeof ContractsIdRouteImport
      parentRoute: typeof ContractsRoute
    }
  }
}

interface ContractsRouteChildren {
  ContractsIdRoute: typeof ContractsIdRoute
  ContractsIndexRoute: typeof ContractsIndexRoute
}

const ContractsRouteChildren: ContractsRouteChildren = {
  ContractsIdRoute: ContractsIdRoute,
  ContractsIndexRoute: ContractsIndexRoute,
}

const ContractsRouteWithChildren = ContractsRoute._addFileChildren(
  ContractsRouteChildren,
)

interface SettingsRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface TenantsRouteChildren {
  TenantsIdRoute: typeof TenantsIdRoute
  TenantsIndexRoute: typeof TenantsIndexRoute
}

const TenantsRouteChildren: TenantsRouteChildren = {
  TenantsIdRoute: TenantsIdRoute,
  TenantsIndexRoute: TenantsIndexRoute,
}

const TenantsRouteWithChildren =
  TenantsRoute._addFileChildren(TenantsRouteChildren)

interface UnitsRouteChildren {
  UnitsIdRoute: typeof UnitsIdRoute
  UnitsIndexRoute: typeof UnitsIndexRoute
}

const UnitsRouteChildren: UnitsRouteChildren = {
  UnitsIdRoute: UnitsIdRoute,
  UnitsIndexRoute: UnitsIndexRoute,
}

const UnitsRouteWithChildren = UnitsRoute._addFileChildren(UnitsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContractsRoute: ContractsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  NotificationsRoute: NotificationsRoute,
  PaymentsRoute: PaymentsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TenantsRoute: TenantsRouteWithChildren,
  UnitsRoute: UnitsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
